# 2021 Policy Data

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('./data/data_policy_2022.csv')
df

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20220101,1.0,1.0,NaN,0.0,...,41.67,41.67,50.0,50.0,44.27,44.27,47.02,47.02,25.0,25.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20220102,1.0,1.0,NaN,0.0,...,41.67,41.67,50.0,50.0,44.27,44.27,47.02,47.02,25.0,25.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20220103,1.0,1.0,NaN,0.0,...,41.67,41.67,50.0,50.0,44.27,44.27,47.02,47.02,25.0,25.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20220104,1.0,1.0,NaN,0.0,...,41.67,41.67,50.0,50.0,44.27,44.27,47.02,47.02,25.0,25.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20220105,1.0,1.0,NaN,0.0,...,41.67,41.67,50.0,50.0,44.27,44.27,47.02,47.02,25.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37123,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220410,2.0,1.0,NaN,2.0,...,61.11,61.11,65.0,65.0,51.56,51.56,58.93,58.93,0.0,0.0
37124,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220411,2.0,1.0,NaN,2.0,...,61.11,61.11,65.0,65.0,51.56,51.56,58.93,58.93,0.0,0.0
37125,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220412,NaN,NaN,NaN,NaN,...,NaN,61.11,NaN,65.0,NaN,51.56,NaN,58.93,NaN,0.0
37126,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220413,NaN,NaN,NaN,NaN,...,NaN,61.11,NaN,65.0,NaN,51.56,NaN,58.93,NaN,0.0
37127,Zimbabwe,ZWE,NaN,NaN,NAT_TOTAL,20220414,NaN,NaN,NaN,NaN,...,NaN,61.11,NaN,65.0,NaN,51.56,NaN,58.93,NaN,0.0

## China policy data

In [3]:
df_CHN = df.loc[df['CountryName']=='China']
df_CHN

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
8320,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220101,1.0,1.0,NaN,1.0,...,56.94,56.94,65.00,65.00,59.11,59.11,67.56,67.56,0.0,0.0
8321,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220102,1.0,1.0,NaN,1.0,...,56.94,56.94,65.00,65.00,59.11,59.11,67.56,67.56,0.0,0.0
8322,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220103,1.0,1.0,NaN,1.0,...,56.94,56.94,65.00,65.00,59.11,59.11,67.56,67.56,0.0,0.0
8323,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220104,1.0,1.0,NaN,1.0,...,56.94,56.94,65.00,65.00,59.11,59.11,67.56,67.56,0.0,0.0
8324,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220105,1.0,1.0,NaN,1.0,...,56.94,56.94,65.00,65.00,59.11,59.11,67.56,67.56,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11643,China,CHN,NaN,NaN,NAT_TOTAL,20220410,3.0,0.0,NaN,2.0,...,75.46,75.46,70.95,70.95,77.34,77.34,79.46,79.46,62.5,62.5
11644,China,CHN,NaN,NaN,NAT_TOTAL,20220411,NaN,NaN,NaN,NaN,...,NaN,75.46,NaN,70.95,NaN,77.34,NaN,79.46,NaN,62.5
11645,China,CHN,NaN,NaN,NAT_TOTAL,20220412,NaN,NaN,NaN,NaN,...,NaN,75.46,NaN,70.95,NaN,77.34,NaN,79.46,NaN,62.5
11646,China,CHN,NaN,NaN,NAT_TOTAL,20220413,NaN,NaN,NaN,NaN,...,NaN,75.46,NaN,70.95,NaN,77.34,NaN,79.46,NaN,62.5
11647,China,CHN,NaN,NaN,NAT_TOTAL,20220414,NaN,NaN,NaN,NaN,...,NaN,75.46,NaN,70.95,NaN,77.34,NaN,79.46,NaN,62.5

In [12]:
df_CHN.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
8320,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220101,1.0,1.0,NaN,1.0,...,56.94,56.94,65.0,65.0,59.11,59.11,67.56,67.56,0.0,0.0
8321,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220102,1.0,1.0,NaN,1.0,...,56.94,56.94,65.0,65.0,59.11,59.11,67.56,67.56,0.0,0.0
8322,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220103,1.0,1.0,NaN,1.0,...,56.94,56.94,65.0,65.0,59.11,59.11,67.56,67.56,0.0,0.0
8323,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220104,1.0,1.0,NaN,1.0,...,56.94,56.94,65.0,65.0,59.11,59.11,67.56,67.56,0.0,0.0
8324,China,CHN,Anhui,CHN_AH,STATE_TOTAL,20220105,1.0,1.0,NaN,1.0,...,56.94,56.94,65.0,65.0,59.11,59.11,67.56,67.56,0.0,0.0

In [ ]:
### Numbers of columns

In [21]:
df_CHN.shape[1]

86

In [ ]:
### Numbers of lines

In [23]:
df_CHN.shape[0]

3328

In [25]:
len(df_CHN)

3328

In [4]:
df_CHN.to_csv(f'./data/2022_policy/CHN_policy_2022.csv')

## America policy data

In [5]:
df_USA = df.loc[df['CountryCode']=='USA']
df_USA

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
30784,United States,USA,NaN,NaN,NAT_TOTAL,20220101,2.0,0.0,NaN,2.0,...,53.24,53.24,63.81,63.81,52.6,52.6,60.12,60.12,0.0,0.0
30785,United States,USA,NaN,NaN,NAT_TOTAL,20220102,2.0,0.0,NaN,2.0,...,53.24,53.24,63.81,63.81,52.6,52.6,60.12,60.12,0.0,0.0
30786,United States,USA,NaN,NaN,NAT_TOTAL,20220103,2.0,0.0,NaN,2.0,...,53.24,53.24,63.81,63.81,52.6,52.6,60.12,60.12,0.0,0.0
30787,United States,USA,NaN,NaN,NAT_TOTAL,20220104,2.0,0.0,Several school districts across the country ar...,2.0,...,53.24,53.24,63.81,63.81,52.6,52.6,60.12,60.12,0.0,0.0
30788,United States,USA,NaN,NaN,NAT_TOTAL,20220105,2.0,0.0,NaN,2.0,...,53.24,53.24,63.81,63.81,52.6,52.6,60.12,60.12,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36187,United States,USA,Wyoming,US_WY,STATE_TOTAL,20220410,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36188,United States,USA,Wyoming,US_WY,STATE_TOTAL,20220411,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36189,United States,USA,Wyoming,US_WY,STATE_TOTAL,20220412,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36190,United States,USA,Wyoming,US_WY,STATE_TOTAL,20220413,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36191,United States,USA,Wyoming,US_WY,STATE_TOTAL,20220414,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_USA.to_csv(f'./data/2022_policy/USA_policy_2022.csv')

## Italy policy data

In [7]:
df_ITA = df.loc[df['CountryName']=='Italy']
df_ITA

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
21112,Italy,ITA,NaN,NaN,NAT_TOTAL,20220101,2.0,1.0,NaN,3.0,...,76.85,76.85,88.1,88.10,82.29,82.29,83.33,83.33,75.0,75.0
21113,Italy,ITA,NaN,NaN,NAT_TOTAL,20220102,2.0,1.0,NaN,3.0,...,76.85,76.85,88.1,88.10,82.29,82.29,83.33,83.33,75.0,75.0
21114,Italy,ITA,NaN,NaN,NAT_TOTAL,20220103,2.0,1.0,"no changes in policy, green passes are still r...",3.0,...,76.85,76.85,88.1,88.10,82.29,82.29,83.33,83.33,75.0,75.0
21115,Italy,ITA,NaN,NaN,NAT_TOTAL,20220104,2.0,1.0,NaN,3.0,...,76.85,76.85,88.1,88.10,82.29,82.29,83.33,83.33,75.0,75.0
21116,Italy,ITA,NaN,NaN,NAT_TOTAL,20220105,2.0,1.0,NaN,3.0,...,76.85,76.85,88.1,88.10,82.29,82.29,83.33,83.33,75.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21211,Italy,ITA,NaN,NaN,NAT_TOTAL,20220410,NaN,NaN,NaN,NaN,...,NaN,53.70,NaN,71.43,NaN,64.58,NaN,66.67,NaN,50.0
21212,Italy,ITA,NaN,NaN,NAT_TOTAL,20220411,NaN,NaN,NaN,NaN,...,NaN,53.70,NaN,71.43,NaN,64.58,NaN,66.67,NaN,50.0
21213,Italy,ITA,NaN,NaN,NAT_TOTAL,20220412,NaN,NaN,NaN,NaN,...,NaN,53.70,NaN,71.43,NaN,64.58,NaN,66.67,NaN,50.0
21214,Italy,ITA,NaN,NaN,NAT_TOTAL,20220413,NaN,NaN,NaN,NaN,...,NaN,53.70,NaN,71.43,NaN,64.58,NaN,66.67,NaN,50.0
21215,Italy,ITA,NaN,NaN,NAT_TOTAL,20220414,NaN,NaN,NaN,NaN,...,NaN,53.70,NaN,71.43,NaN,64.58,NaN,66.67,NaN,50.0

In [8]:
df_ITA.to_csv(f'./data/2022_policy/ITA_policy_2022.csv')

## UK policy data

In [9]:
df_UK = df.loc[df['CountryName']=='United Kingdom']
df_UK

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_School closing,C1_Flag,C1_Notes,C2_Workplace closing,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
14560,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220101,1.0,1.0,NaN,2.0,...,48.61,48.61,58.33,58.33,51.04,51.04,54.76,54.76,25.0,25.0
14561,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220102,1.0,1.0,NaN,2.0,...,48.61,48.61,58.33,58.33,51.04,51.04,54.76,54.76,25.0,25.0
14562,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220103,1.0,1.0,NaN,2.0,...,48.61,48.61,58.33,58.33,51.04,51.04,54.76,54.76,25.0,25.0
14563,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220104,1.0,1.0,Face coverings required in schools http://w...,2.0,...,48.61,48.61,58.33,58.33,51.04,51.04,54.76,54.76,25.0,25.0
14564,United Kingdom,GBR,NaN,NaN,NAT_TOTAL,20220105,1.0,1.0,NaN,2.0,...,48.61,48.61,58.33,58.33,51.04,51.04,54.76,54.76,25.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15075,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220410,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15076,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220411,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15077,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220412,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15078,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220413,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15079,United Kingdom,GBR,Wales,UK_WAL,STATE_TOTAL,20220414,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_UK.to_csv(f'./data/2022_policy/UK_policy_2022.csv')